      SELECT * FROM SUDOQ..CLIENTE
      SELECT * FROM SUDOQ..CLIENTEPAGO
	  SELECT * FROM SUDOQ..SUCESOLOG

   -- INSERT INTO SUDOQ..CLIENTE VALUES ('252F9625-25BD-451B-88DC-2B980AB1AEFE','efrainmejiasc@hotmail.com','1234',GetDate(),GetDate(),GetDate(),GetDate(),1,1,'ES-es')
   -- INSERT INTO SUDOQ..CLIENTEPAGO VALUES (1, GETDATE(),DATEADD(DAY, 30, GETDATE()),15,2,16)
   -- UPDATE CLIENTEPAGO SET FechaVencimiento = DATEADD(DAY, 30, GETDATE()), IdCliente = 1
   -- TRUNCATE TABLE SUDOQ..SucesoLog
   -- TRUNCATE TABLE SUDOQ..CLIENTEPAGO
   -- TRUNCATE TABLE SUDOQ..CLIENTE





